on:
  push:
    branches:
      - main
    paths:
      - app1/**

name: website1
jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
          persist-credentials: false

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      working-directory: app1
      run: |
        docker build -t 663427703437.dkr.ecr.us-east-1.amazonaws.com/app1:$GITHUB_RUN_NUMBER .
        docker push 663427703437.dkr.ecr.us-east-1.amazonaws.com/app1:$GITHUB_RUN_NUMBER
        echo "::set-output name=image::663427703437.dkr.ecr.us-east-1.amazonaws.com/app1:$GITHUB_RUN_NUMBER"
