on:
  push:
    branches:
      - main
    paths:
      - app1/**

name: website1
jobs:
  deploy:
    name: test
    runs-on: ubuntu-latest
    
    steps:
    - name: echo
      run: |
        echo "CICD website 1"
